apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-http-server
  namespace: webserver
spec:
  project: default
  source:
    repoURL: 'https://github.com/bramlak/origoss-task.git'
    targetRevision: HEAD
    path: kubernetes  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



